build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
filter:
  excluded_paths:
    - 'resources/*'
    - 'tests/*'
checks:
  php: true
