version: "3"

services:
  mariadb:
    container_name: "koenavel_mariadb"
    image: wodby/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: koenavelRootPass
      MYSQL_DATABASE: koenavel
      MYSQL_USER: koenavelUser
      MYSQL_PASSWORD: koenavelPass
  php:
    container_name: "koenavel_php"
    image: wodby/php:latest
    depends_on:
      - mariadb
      - redis
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      MYSQL_DATABASE: koenavel
      MYSQL_HOSTNAME: mariadb
      MYSQL_USER: koenavelUser
      MYSQL_PASSWORD: koenavelPass
      REDIS_HOST: redis
    volumes:
      - ./:/var/www/html:cached
  nginx:
    container_name: "koenavel_nginx"
    image: wodby/nginx:latest
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web/
      NGINX_VHOST_PRESET: php
    volumes:
      - ./:/var/www/html:cached
  redis:
    container_name: "koenavel_redis"
    image: wodby/redis:latest
  mailhog:
    container_name: "koenavel_mailhog"
    image: mailhog/mailhog:latest
